version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

workflows:
  buildAndDeploy:
    jobs:
      - node/run:
          npm-run: build
      - aws-s3/copy:
          filters:
            branches:
              only:
                - master
          requires:
            - node/run
          from: dist/
          to: s3://shop.craftonomy.net
          arguments: --recursive